// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rentals.Infrastructure.Persistence;

#nullable disable

namespace Rentals.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RentalsDbContext))]
    [Migration("20260609031708_InitialRentals")]
    partial class InitialRentals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rentals.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal>("FreightFixedPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("freight_fixed_price_snapshot");

                    b.Property<decimal>("FreightSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("freight_subtotal");

                    b.Property<bool>("IncludeFreight")
                        .HasColumnType("boolean")
                        .HasColumnName("include_freight");

                    b.Property<bool>("IncludeOperator")
                        .HasColumnType("boolean")
                        .HasColumnName("include_operator");

                    b.Property<decimal>("ListingDailyPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("listing_daily_price_snapshot");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<decimal>("MachineSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("machine_subtotal");

                    b.Property<decimal>("OperatorDailyPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("operator_daily_price_snapshot");

                    b.Property<decimal>("OperatorSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("operator_subtotal");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("renter_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer")
                        .HasColumnName("total_days");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_rentals_listing_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_rentals_provider_id");

                    b.HasIndex("RenterId")
                        .HasDatabaseName("ix_rentals_renter_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rentals_status");

                    b.HasIndex("ListingId", "Status")
                        .HasDatabaseName("ix_rentals_listing_id_status");

                    b.HasIndex("ProviderId", "Status")
                        .HasDatabaseName("ix_rentals_provider_id_status");

                    b.HasIndex("RenterId", "Status")
                        .HasDatabaseName("ix_rentals_renter_id_status");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_rentals_start_date_end_date");

                    b.ToTable("rentals", null, t =>
                        {
                            t.HasCheckConstraint("ck_rentals_amounts_non_negative", "machine_subtotal > 0 AND total_amount > 0");

                            t.HasCheckConstraint("ck_rentals_freight_prices_non_negative", "freight_fixed_price_snapshot >= 0 AND freight_subtotal >= 0");

                            t.HasCheckConstraint("ck_rentals_listing_daily_price_positive", "listing_daily_price_snapshot > 0");

                            t.HasCheckConstraint("ck_rentals_operator_prices_non_negative", "operator_daily_price_snapshot >= 0 AND operator_subtotal >= 0");

                            t.HasCheckConstraint("ck_rentals_owner_and_renter_must_be_different", "provider_id <> renter_id");

                            t.HasCheckConstraint("ck_rentals_total_amount_consistency", "total_amount = machine_subtotal + operator_subtotal + freight_subtotal");

                            t.HasCheckConstraint("ck_rentals_total_days_positive", "total_days > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
